### ISSUE TITLE
DropDown data-value=0 is treated as null

### ISSUE THREAD

**Issue by acicovic** [atk4/ui#781]
When we fill a DropDown with data, its data-value property is populated with each item's ID. Although rare, the value "0" is sometimes a legitimate choice for a database ID column value.

When this happens, ATK UI will consider 0 as null during its dropdown validation, and display a "must not be null" validation error if 0 is selected. However, the user has made a valid selection and zero is not the same thing as null.

P.S: This also reminds of #755 which is also an issue of how a zero value is handled as null. So zero handling should be perhaps reconsidered in ATK and fix it wherever it doesn't work correctly.

**Comment by acicovic** [comment]
Another case when this issue is a blocker, is when a value of 0 is declared in a model. For example
```
// Code in model addFields()

['gender_id',
    'required' => true,
    'values' => [0 => 'Female', 1 => 'Male'],
]
```
Even if you don't specify the numeric values. selection "Female" will still be blocked because it will be evaluated to 0.

**Comment by PhilippGrashoff** [comment]
This was there a while ago, I fixed it, but recent changes obviously brought it back...
#618 
So if this is fixed again, we really need a test for it. My bad I didnt write a test also when writing the fix

**Comment by romaninsh** [comment]
Leaving this to you then ;) make a test this time.

**Comment by PhilippGrashoff** [comment]
@acicovic without diving into this as I am not on newest versions yet: Does setting 
`type` => `integer` help with the DropDown?

**Comment by acicovic** [comment]
Setting `'type' => 'integer'` results in no difference.

**Comment by PhilippGrashoff** [comment]
I see Imants is already on it, thanks @DarkSide666 !

**Comment by romaninsh** [comment]
Test-case here: https://github.com/atk4/ui/pull/783/files#diff-f2ca0641b3256c64a192f93071ce4ba0R162, @acicovic please check!

**Comment by acicovic** [comment]
It doesn't work for me and brings back #760.

**Comment by acicovic** [comment]
#760 is fixed. @DarkSide666 as this is essentially a data issue, is it tracked somewhere in the data repository? If yes let's add a reference to that issue here.

**Comment by DarkSide666** [comment]
It should be somewhere in this huge model field class refactor branch https://github.com/atk4/data/pull/375, but that PR is still not 100% ready for merge (only for version 2.0).

**Comment by mvorisek** [comment]
@acicovic still valid? can you provide steps to replicate on demos?

**Comment by acicovic** [comment]
@mvorisek give me some days and I'll get back to you.

**Comment by acicovic** [comment]
Haven't tested this yet but I see no indication that this would be fixed as atk4/data#375 is not merged yet. This is more of a data issue rather than UI, so it could perhaps make sense to open an issue there.

@mvorisek have you tried this and it works for you?

**Comment by mvorisek** [comment]
@acicovic please provide steps how to reproduce on demos or fork this repo and update it with some minimalistic example. We can then fix it quickly if the issue is on Atk side.

**Comment by acicovic** [comment]
I never tested this and it is unlikely that I will for the time being. If anyone wants to take a go at it, please go ahead.

**Comment by mkrecek234** [comment]
It's true that the dropdown or cascadedropdown or lookup does not accept 0 values für type => integer ('must not be null'). So this should be fixed.

**Comment by mvorisek** [comment]
Please provide step by step test scenario to replicate.

**Comment by mvorisek** [comment]
I tested this demo code:
```
$form = \Atk4\Ui\Form::addTo($app);
$form->addControl(
    'x',
    [\Atk4\Ui\Form\Control\Dropdown::class],
    ['type' => 'integer', 'mandatory' => true, 'values' => [0 => 'Female', 1 => 'Male']]
);
$form->onSubmit(function (\Atk4\Ui\Form $form) {
    return $form->getControl('x')->field;
});
```
and it works with `integer` and  `string` type.

⚠️ In you code, you used `required`, which rejects zeros. Just use `mandatory`.
